config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  
  get 'index' => 'home#index'
  get 'about' => 'home#about'
  get 'contact-us' => 'home#contact-us'
  get 'search' => 'home#search-result'
  get 'about1' => 'home#about1'
  get 'index3' => 'home#index3'
  post '/write' => 'home#write'
  get 'list' => 'home#list'
  get 'user_page' => 'home#user_page'
  
  get 'user' => 'home#user-test'
  
  
  get ':controller(/:action(/:id))'
  post ':controller(/:action(/:id))'
  
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  

end

app/controllers/home_controller.rb
require 'mailgun'
class HomeController < ApplicationController
  
  def index
    @hackers_all = Hacker.where.not(level: 0)
    @pagoda_all = Pagoda.where.not(level: 0)
    @young_all = Young.where.not(level: 0)
    
    @hackers_num = Hacker.where.not(level: 0).length
    @pagoda_num = Pagoda.where.not(level: 0).length
    @young_num = Young.where.not(level: 0).length
  end
  
  def index_all
    @hackers_all = Hacker.where.not(level: 0)
    @pagoda_all = Pagoda.where.not(level: 0)
    @young_all = Young.where.not(level: 0)
    
    @hackers_num = Hacker.where.not(level: 0).length
    @pagoda_num = Pagoda.where.not(level: 0).length
    @young_num = Young.where.not(level: 0).length
  end
  
  def index_result

    @filtered_hackers = Hacker.where("subject In (?) and loc In (?) and week In (?) and level In (?)",
    params[:subject], params[:loc], params[:week], params[:level])
    
    @filtered_pagoda = Pagoda.where("subject In (?) and loc In (?) and week In (?) and level In (?)",
    params[:subject], params[:loc], params[:week], params[:level])
    
    @filtered_young = Young.where("subject In (?) and loc In (?) and week In (?) and level In (?)",
    params[:subject], params[:loc], params[:week], params[:level])
    
    @hackers_all = Hacker.where.not(level: 0)
    @pagoda_all = Pagoda.where.not(level: 0)
    @young_all = Young.where.not(level: 0)
    
    @hackers_num = Hacker.where.not(level: 0).length
    @pagoda_num = Pagoda.where.not(level: 0).length
    @young_num = Young.where.not(level: 0).length
    
    
    #찜하기 기능
    if params[:type] == "hacker_wish"
      current_user.follow(Hacker.find(params[:lecture_id]))
      redirect_to :back

    elsif params[:type] == "hacker_unwish"
      current_user.stop_following(Hacker.find(params[:lecture_id]))
      redirect_to :back
    end
    
    if params[:type] == "pagoda_wish"
      current_user.follow(Pagoda.find(params[:lecture_id]))
      redirect_to :back

    elsif params[:type] == "pagoda_unwish"
      current_user.stop_following(Pagoda.find(params[:lecture_id]))
      redirect_to :back
    end
    
    if params[:type] == "young_wish"
      current_user.follow(Young.find(params[:lecture_id]))
      redirect_to :back

    elsif params[:type] == "young_unwish"
      current_user.stop_following(Young.find(params[:lecture_id]))
      redirect_to :back
    end
    
    # redirect_to "/home/index_result"
    
  end
  
  def user_page
    @hackers = Hacker.all
    @pagoda = Pagoda.all
    @young = Young.all
    
    #찜하기 기능
    if params[:type] == "hacker_wish"
      current_user.follow(Hacker.find(params[:lecture_id]))
      redirect_to :back

    elsif params[:type] == "hacker_unwish"
      current_user.stop_following(Hacker.find(params[:lecture_id]))
      redirect_to :back
    end
    
    if params[:type] == "pagoda_wish"
      current_user.follow(Pagoda.find(params[:lecture_id]))
      redirect_to :back

    elsif params[:type] == "pagoda_unwish"
      current_user.stop_following(Pagoda.find(params[:lecture_id]))
      redirect_to :back
    end
    
    if params[:type] == "young_wish"
      current_user.follow(Young.find(params[:lecture_id]))
      redirect_to :back

    elsif params[:type] == "young_unwish"
      current_user.stop_following(Young.find(params[:lecture_id]))
      redirect_to :back
    end
    
  end
    
  # def about
  #   @title = params[:title]
  #   @receiver = params[:email]
  #   @content = params[:content]s
  #   mg_client = Mailgun::Client.new("key-5c1dde76bef60438458d6afe28c6405c") #메일보내기
  #                     message_params =  {
  #                                       from: "jiyoni1225@gmail.com",
  #                                       to: "jiyoni1225@gmail.com",
  #                                       subject: @title,
  #                                       text: @content
                      
  #                     result = mg_client.send_message('sandbox0483375709ed4b5aa15e77d809433a11', message_params).to_h!
                      
  #                     message_id = result['id']
  #                     message = result['message']
    
    
  # end
    def write
        @title = params[:title]
        
        @receiver =  params[:email]
        @content = params[:content]
        mg_client = Mailgun::Client.new("key-5c1dde76bef60438458d6afe28c6405c")
        message_params =  {
                          from: 'YOJINI@love.com',
                          to: 'jiyoni1225@gmail.com',
                       #   to:   @address,
                          subject: @title,
                          text:    @content
                          }
        result = mg_client.send_message('sandbox0483375709ed4b5aa15e77d809433a11.mailgun.org', message_params).to_h!
        # message_id = result['id']
        # message = result['message']
        # new_post = Post.new
        # new_post.title = @title
        # new_post.content = @content
        # new_post.email = @address
        # new_post.save
        redirect_to '/about'
    end
    
    def list
        @every_post = Post.all #Post.all.order("id desc")
    end
end

app/helpers/home_helper.rb
module HomeHelper


end

app/views/home/404-page.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
	<title>404 Page-Hotel Finder</title>

	<!-- Bootstrap -->
	<link href="css/bootstrap.min.css" rel="stylesheet" />
	<!-- Main styles -->
	<link href="css/style.css" rel="stylesheet" />
	<!--<link rel="stylesheet/less" href="css/style.less" />-->
	<!-- IE styles -->
	<link href="css/ie.css" rel="stylesheet" />
	<!-- Font Awesome -->
	<link href="css/font-awesome.min.css" rel="stylesheet" />
	<!-- Jquery UI -->
	<link href="css/jquery-ui.css" rel="stylesheet" />
	<!-- OWL Carousel -->
	<link href="css/owl.carousel.css" rel="stylesheet" />
	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>
<body class="htlfndr-404-page">

<div class="htlfndr-wrapper">
	<header>
		<div class="container text-center">
			<a class="htlfndr-logo" href="index.html">
				<img src="images/logo.png" alt="Logo" />
				<p class="htlfndr-logo-text">hotel <span>finder</span></p>
			</a>
		</div>
					
		<noscript><h2>You have JavaScript disabled!</h2></noscript>
	</header>

	<!-- Start of main content -->
	<div class="container">
		
		<main id="htlfndr-main-content" class="htlfndr-404-content text-center" role="main">	
			<p class="htlfndr-404-title">The page you were looking for could not be found</p>
			<p class="htlfndr-404">404</p>
			<a href="index.html" class="htlfndr-404-btn"><i class="fa fa-home"></i>Go to Homepage</a>
		</main><!-- .htlfndr-hotel-single-content -->
		</div><!-- .container -->
	<!-- End of main content -->

	<!-- Start of the Footer -->
	<footer class="htlfndr-footer">
		<div class="container">
		<div class="navbar-collapse fail-page text-center" id="htlfndr-main-nav">

						<ul class="nav navbar-nav">
							<li>
								<a href="index.html">home</a>
							</li>
							<li><a href="elements.html">elements</a></li>
							<li>
								<a href="blog-index.html">blog</a>
							</li>
							<li>
								<a href="about-us.html">about</a>
							</li>
							<li>
								<a href="user-page.html">user profile</a>
							</li>
						</ul>
					</div><!-- .collapse.navbar-collapse -->
				</div>
	</footer>
</div><!-- .htlfndr-wrapper -->

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="js/jquery-1.11.3.min.js"></script>
<!-- Include Jquery UI script file -->
<script src="js/jquery-ui.min.js"></script>
<!-- Include Query UI Touch Punch is a small hack that enables the use
		 of touch events on sites using the jQuery UI user interface library. -->
<script src="js/jquery.ui.touch-punch.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="js/bootstrap.min.js"></script>
<!-- Include Touch Menu Hover script file -->
<script src="js/jquery.ui.touch-punch.min.js"></script>
<!-- Include Owl Carousel script file -->
<script src="js/owl.carousel.min.js"></script>
<!-- Include main script file -->
<script src="js/script.js"></script>

<!--<script src="js/less.min.js" ></script> -->
</body>
</html>

app/views/home/about1.html.erb
<div class="container">
  <h2>Bootstrap 3.1.0 - Modal Demo</h2>

  <div class="row text-center">
      <h3>The Basic Modal</h3>
      <a href="#" class="btn btn-lg btn-success" data-toggle="modal" data-target="#basicModal">Click to open Modal</a>
  </div>
  <hr>
  <div class="row text-center">
      <h3>The Large Modal</h3>
      <a href="#" class="btn btn-lg btn-primary" data-toggle="modal" data-target="#largeModal">Click to open Modal</a>
  </div>
  <hr>
  <div class="row text-center">
      <h3>The Small Modal</h3>
      <a href="#" class="btn btn-lg btn-danger" data-toggle="modal" data-target="#smallModal">Click to open Modal</a>
  </div>

</div>

<div class="modal fade" id="basicModal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Basic Modal</h4>
      </div>
      <div class="modal-body">
        <h3>Modal Body</h3>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="largeModal" tabindex="-1" role="dialog" aria-labelledby="largeModal" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Large Modal</h4>
      </div>
      <div class="modal-body">
        <h3>Modal Body</h3>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="smallModal" tabindex="-1" role="dialog" aria-labelledby="smallModal" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Small Modal</h4>
      </div>
      <div class="modal-body">
        <h3>Modal Body</h3>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

<p class="p">Demo by Syed Fazle Rahman. <a href="http://www.sitepoint.com/understanding-bootstrap-modals/" target="_blank">See article</a>.</p>

app/views/home/list.html.erb
<html>


<h1> ♡~보낸 화살들~♡ </h1>

<% @every_post.each do |p| %>
    제목 : <%= p.title %> <br>
    내용 : <%= p.content %> <br>
    화살 받은 사람 : <%= p.email %> <br>
    <hr>
<%end%>


<div class="label label-warning" style="text-align:center" ><h4><a href="/"> ♡~화살 쏘기~♡ </a></h4></div>

app/views/home/user_page.html.erb
<div class="htlfndr-wrapper htlfndr-user-page">


	<!-- Start of main content -->
	<div class="container">

		<main id="htlfndr-main-content" role="main">
			<div class="row htlfndr-user-tabs htlfndr-credit-card-page">
				
				<div class="htlfndr-user-person-navigation-wrapper col-sm-4 col-md-3">
					<div class="htlfndr-user-person-navigation">
						
						<h3 class="htlfndr-user-name"><%= current_user.username %></h3>
						<% if current_user.sign_in_count < 10 %>
							<h6 class="htlfndr-user-membership">Bronze
							<i class="fa fa-question-circle q-pop yyy" aria-hidden="true"><span>toss에 로그인한 횟수에 따라 회원등급이 올라갑니다</span></i></h6>
						<% elsif current_user.sign_in_count < 20 %>
							<h6 class="htlfndr-user-membership">Silver</h6>
							<i class="fa fa-question-circle q-pop yyy" aria-hidden="true"><span>toss에 로그인한 횟수에 따라 회원등급이 올라갑니다</span></i>
						<% elsif current_user.sign_in_count < 30 %>
							<h6 class="htlfndr-user-membership">Gold</h6>
							<i class="fa fa-question-circle q-pop yyy" aria-hidden="true"><span>toss에 로그인한 횟수에 따라 회원등급이 올라갑니다</span></i>
						<% elsif current_user.sign_in_count < 40 %>
							<h6 class="htlfndr-user-membership">Platinum</h6>
							<i class="fa fa-question-circle q-pop yyy" aria-hidden="true"><span>toss에 로그인한 횟수에 따라 회원등급이 올라갑니다</span></i>
						<% elsif current_user.sign_in_count < 50 %>
							<h6 class="htlfndr-user-membership">Diamond</h6>
							<i class="fa fa-question-circle q-pop yyy" aria-hidden="true"><span>toss에 로그인한 횟수에 따라 회원등급이 올라갑니다</span></i>
						<% elsif current_user.sign_in_count > 49 %>
							<h6 class="htlfndr-user-membership">Original Cheese</h6>
							<i class="fa fa-question-circle q-pop yyy" aria-hidden="true"><span>toss에 로그인한 횟수에 따라 회원등급이 올라갑니다</span></i>
						<% end %>
						
						
	
						<ul role="tablist">
							<!--<li><a href="#htlfndr-user-tab-1"><i class="fa fa-user"></i> personal info</a></li>-->
							<li><a href="#htlfndr-user-tab-2"><i class="fa fa-heart-o"></i> wishlist</a></li>
							<li><a href="#htlfndr-user-tab-3"><i class="fa fa-wrench"></i> settings</a></li>
						</ul>
					</div><!-- .htlfndr-user-person-navigation -->
				</div><!-- .htlfndr-user-person-navigation-wrapper -->
				
				<div class="htlfndr-user-panel col-md-8 col-sm-8 htlfndr-setting-page" id="htlfndr-user-tab-2">
					<div class="htlfndr-setting">
						
							<h2>My <b>Score</b></h2>
						<div class="row htlfndr-counters">
							<div class="col-md-3 col-sm-6">
								<div class="htlfndr-counter-block">
										<div class="htlfndr-icon-holder1">
												<h2 class='test_type'>TOEIC</h2>
											<!--<i class="fa fa-plane"></i>-->
										</div>
									<dl class="htlfndr-counter-numbers">
										<dt> <%=current_user.toeic_score%> </dt>
										<dd>score</dd>
									</dl>
								</div><!-- .htlfndr-counter-block -->
							</div>
							<div class="col-md-3 col-sm-6">
								<div class="htlfndr-counter-block">
									<div class="htlfndr-icon-holder2">
										<h2 class='test_type'>TOEFL</h2>
										<!--<i class="fa fa-building-o"></i>-->
									</div>
									<dl class="htlfndr-counter-numbers">
										<dt><%=current_user.toefl_score%></dt>
										<dd>score</dd>
									</dl>
								</div><!-- .htlfndr-counter-block -->
							</div>
							<div class="col-md-3 col-sm-6">
								<div class="htlfndr-counter-block">
									<div class="htlfndr-icon-holder3">
										<h2 class='test_type'>TEPS</h2>
										<!--<i class="fa fa-globe"></i>-->
									</div>
									<dl class="htlfndr-counter-numbers">
										<dt><%= current_user.teps_score%></dt>
										<dd>score</dd>
									</dl>
								</div><!-- .htlfndr-counter-block -->
							</div>
							<div class="col-md-3 col-sm-6">
								<div class="htlfndr-counter-block">
									<div class="htlfndr-icon-holder4">
										<h2 class='test_type'>토스</h2>
										<!--<i class="fa fa-map-marker"></i>-->
									</div>
									<dl class="htlfndr-counter-numbers">
										<dt><%=current_user.tos_level%></dt>
										<dd>level</dd>
									</dl>
								</div><!-- .htlfndr-counter-block -->
							</div>
							<!--<p><a href = "#htlfndr-user-tab-3", class = "move_a">setting 페이지로 이동해 점수를 입력해보세요</a></p>-->
						</div><!-- .row.htlfndr-counters -->
					<!--</div>-->
					
				<!--</div><!-- #htlfndr-user-tab-1 -->
				
				<!--<div class="htlfndr-user-panel col-md-8 col-sm-8" id="htlfndr-user-tab-2">-->
				<!--	<div class="htlfndr-setting">-->
							<hr>
							
							<h2>My <b>Wishlist</b></h2>
									<table class="result_table">
									<colgroup>
								      <col width="7%">
								      <col width="10%">
								      <col width="23%">
								      <col width="27%">
								      <col width="10%">
								      <col width="13%">
								      <col width="10%">
								    </colgroup>
								    <thead>
								    <tr>
								        <th scope="cols">과목군</th>
								        <th scope="cols">위치(학원)</th>
								        <th scope="cols">시간</th>
								        <th scope="cols">강의명</th>
								        <th scope="cols">강사</th>
								        <th scope="cols">가격</th>
								        <th scope="cols">찜</th>
								    </tr>
								    </thead>
								    
								    <tbody>
								    	<% if current_user.follow_count == 0 %>
									    	<tr>
									    		<td></td>
									    		<td></td>
									    		<td></td>
									    		<td>찜한 강의가 없습니다!</td>
									    		<td></td>
									    		<td></td>
									    		<td></td>
									    	</tr>
										<% else %>
										<% @hackers.each do |l| %>
											<% if l.followed_by?(current_user) == true %>
											<tr>
												<% name = ["해커스"] %>
												<% loc = ["강남", "종로"] %>
												<% subject = ["토플", "토익", "토스"] %>
												<% level = ["기초","필수","입문","기본","중급","정규","실전"] %>
												<% week = ["주 5일반", "월수금반", "화목금반", "주말반"] %>
												<% time = ["아침", "오전", "오후", "저녁"] %>
												
												<td><%= subject[l.subject-1] %></td>
												<td><%= name[l.name-1] %><br>(<%= loc[l.loc-1] %>)</td>
												<td><%= l.day %> <br> (<%= week[l.week-1] %>) </td>
												<td><a href="http://www.hackers.ac<%= l.link %>" target="_blank" class="lecture_go"><%= l.title %><i class="fa fa-search lecture_go_icon" aria-hidden="true"></i></a></td>
												<td><%= l.teacher %></td>
												<td><%= l.price %></td>
									    		<td>
									    			<% if current_user %>
														<% if l.followed_by?(current_user) == true %>
															<%= link_to image_tag("/assets/zzim_ok.gif"),   {:type => "unwish", :lecture_id => l.id}, {:class => 'zzim zzimok'}  %>
														<% end %>
													<% else %>
														<a href="#" data-toggle="modal" data-target="#layerpop"><img class="zzim" src="/assets/zzim_not.gif"></div></a>
													<% end %>
									    		</td>
											</tr>  
											<% end %>
										<% end %>
										
										<% @pagoda.each do |l| %>
											<% if l.followed_by?(current_user) == true %>
											<tr>
										  	  <% name = ["해커스","파고다","와이비엠","영단기"] %>
										      <% loc = ["강남", "종로","신촌"] %>
										      <% subject = ["토플", "토익", "토스"] %>
										      <% week = ["주 5일반", "월수금반", "화목금반", "주말반"] %>
										      <% time = ["아침", "오전", "오후", "저녁"] %>
												
												<td><%= subject[l.subject-1] %></td>
												<td><%= name[l.name-1] %><br>(<%= loc[l.loc-1] %>) </td>
												<td><%= l.day %><br>(<%= week[l.week-1] %>) </td>
												<td><a href="http://m.pagoda21.com/speaker/detail/<%= l.link %>?popup=Y" target="_blank" class="lecture_go"><%= l.title %><i class="fa fa-search lecture_go_icon yy" aria-hidden="true"></i></a></td>
												<td><%= l.teacher %></td>
												<td><%= l.price %></td>
									    		<td>
									    			<% if current_user %>
														<% if l.followed_by?(current_user) == true %>
															<%= link_to image_tag("/assets/zzim_ok.gif"),   {:type => "pagoda_unwish", :lecture_id => l.id}, {:class => 'zzim zzimok'}  %>
														<% else %>
															<%= link_to image_tag("/assets/zzim_not.gif"),   {:type => "pagoda_wish", :lecture_id => l.id}, {:class => 'zzim zzimnot'} %>
														<% end %>
													<% else %>
														<a href="#" data-toggle="modal" data-target="#layerpop"><img class="zzim" src="/assets/zzim_not.gif"></div></a>
													<% end %>
									    		</td>
											</tr>  
											<% end %>
										<% end %>
										
										<% @young.each do |l| %>
    							    	<% if l.followed_by?(current_user) == true %>	
										<tr>
										  <% name = ["해커스","와이비엠","파고다","영단기"] %>
									      <% loc = ["강남", "종로"] %>
									      <% subject = ["토플", "토익", "토스"] %>
									      <% week = ["주 5일반", "월수금반", "화목금반", "주말반"] %>
									      <% time = ["아침", "오전", "오후", "저녁"] %>
											
											<td><%= subject[l.subject-1] %></td>
											<td><%= name[l.name-1] %><br>(<%= loc[l.loc-1] %>) </td>
											<td><%= l.day %><br>(<%= week[l.week-1] %>) </td>
											<td><a href="http://offeng.dangi.co.kr/m/registration/main/view?saleinfo_id=<%= l.link %>" target="_blank" class="lecture_go"><%= l.title %><i class="fa fa-search lecture_go_icon yy" aria-hidden="true"></i></a></td>
											<td><%= l.teacher %></td>
											<td><%= l.price %></td>
								    		<td>
								    			<% if current_user %>
													<% if l.followed_by?(current_user) == true %>
														<%= link_to image_tag("/assets/zzim_ok.gif"),   {:type => "young_unwish", :lecture_id => l.id}, {:class => 'zzim zzimok'}  %>
													<% else %>
														<%= link_to image_tag("/assets/zzim_not.gif"),   {:type => "young_wish", :lecture_id => l.id}, {:class => 'zzim zzimnot'} %>
													<% end %>
												<% else %>
													<a href="#" data-toggle="modal" data-target="#layerpop"><img class="zzim" src="/assets/zzim_not.gif"></div></a>
												<% end %>
								    		</td>
									      </tr> 
									    <% end %>
										<% end %>
										
										<% end %>
								    </tbody>
									</table>
					</div>
				</div><!-- .htlfndr-user-tabs-4-->
				
				<div class="htlfndr-user-panel col-md-8 col-sm-8 htlfndr-setting-page" id="htlfndr-user-tab-3">
					<div class="htlfndr-setting" style = "display: inlne-block;">
						<h2>Change <b>Personal Infomation</b></h2>
							<div class="row2">
								<%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
								<%= f.error_notification %>
									
									<div class="form-inputs">
									  	
									  	<div class="col-md-6 htlfndr-form-setting-cols">
										    <div class = "user_field">
										    Username
										    <%= f.text_field :username, :class => "htlfndr-input" , value:current_user.username%><br/>
										    </div>
										    
										    <div class = "user_field">
										    Password(선택)
										    <%= f.password_field :password, :class => "htlfndr-input", required: false%><br/> 
										    </div>
										    
										    <div class = "user_field">
										    Password Confirmation(선택)
										    <%= f.password_field :password_confirmation, :class => "htlfndr-input", required: false%><br/>
										    </div>
										    
										    <div class = "user_field">
										    Current Password(필수입력)
										    <%= f.password_field :current_password, :class => "htlfndr-input", required: true %><br/>
										    </div>
								 		</div>
									    
									    <div class="col-md-6 htlfndr-form-setting-cols">
										    <div class = "user_field">
										    TOEIC
										    <%= f.text_field :toeic_score, :class => "htlfndr-input", required: false , value:current_user.toeic_score %><br/>
										    </div>
										    
										    <div class = "user_field">
										    TOEFL
										    <%= f.text_field :toefl_score, :class => "htlfndr-input", required: false, value:current_user.toefl_score %><br/>
										    </div>
										    
										    <div class = "user_field">
										    TEPS
										    <%= f.text_field :teps_score, :class => "htlfndr-input", required: false, value:current_user.teps_score %><br/>
										    </div>
										    
										    <div class = "user_field">
										    TOEIC Spaeking
										    <%= f.text_field :tos_level, :class => "htlfndr-input", required: false, value:current_user.tos_level %><br/>
										    </div>
									</div>
									
								<div class="col-md-12 form-actions">
								<%= f.button :submit, "Update", :class => "btn-primary"  %>
								</div>
								<hr>
							</div>
								
								
								
								<h2>Cancel <b>Account</b></h2>	
								<div class = "col-md-12 cancle">
								<%= link_to "CANCLE MY ACCOUNT", registration_path(resource_name), data: { confirm: "Are you sure?" },
								method: :delete, :class => "cancle_account" %>
								<%#= link_to "Back", :back %>	
								</div>
						<% end %>
					</div>
				</div>
						
					</div><!--.htlfndr-setting -->
				</div><!-- .htlfndr-user-tabs-5 -->
				
			
			</div> <!-- .row -->
		</main><!-- #htlfndr-main-content -->
	</div><!-- .container -->
	<!-- End of main content -->




<script>	
		 $(".zzimok").click(function() {
		 	sweetAlert({   title: "찜목록에서 삭제되었습니다!", imageUrl: "/assets/zzim_not.gif", timer: 2000,   showConfirmButton: false, customClass: 'sweet' });
		 });
</script>

app/views/home/write.html.erb
       <h1>문의사항이 전송되었습니다.</h1>

<h2>제목?</h2>
<%= @title %>
<h2>내용?</h2>
<%= @content %>

<h3>앞으로도 좋은 서비스로 보답하겠습니다.</h3>
 <a href="/home/about"><span>about</span></a>