config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  
  get 'index' => 'home#index'
  get 'about' => 'home#about'
  get 'contact-us' => 'home#contact-us'
  get 'search' => 'home#search-result'
  get 'about1' => 'home#about1'
  get 'index3' => 'home#index3'
  post '/write' => 'home#write'
  get 'list' => 'home#list'
  get 'user_page' => 'home#user_page'
  
  get 'user' => 'home#user-test'
  
  
  get ':controller(/:action(/:id))'
  post ':controller(/:action(/:id))'
  
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<!--<meta name="viewport" content="width=device-width, initial-scale=1" />-->
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
	<title>tost | 토스트</title>
	<meta name="description" content="토스트.com, 영어학원계의 쿠차, 모든 영어학원 정보를 한눈에!">
	<!--open graph-->
	<meta property="og:type" content="website">
	<meta property="og:title" content="tost | 토스트">
	<meta property="og:description" content="토스트.com, 영어학원계의 쿠차, 모든 영어학원 정보를 한눈에!">
	<meta property="og:image" content="http://토스트.com/og_image.gif">
	<meta property="og:url" content="http://토스트.com">
	
	<link rel="shortcut icon" href="http://www.yoursite.com/favicon.ico?v=2">
	<link rel="icon" sizes="16x16 32x32" href="/minit.bmp">
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
    <%= csrf_meta_tags %>

    
    <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	
	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
	<link rel="stylesheet" href="assets/stylesheets/glide.core.css">
    <link rel="stylesheet" href="assets/stylesheets/glide.theme.css">
	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    

	<!-- Bootstrap -->
	<link href="/assets/bootstrap.css" rel="stylesheet" />
	<!-- Main styles -->
	<link href="/assets/style.css" rel="stylesheet" />
	<!--<link rel="stylesheet/less" href="/assets/style.less" />-->
	<!-- IE styles -->
	<link href="/assets/ie.css" rel="stylesheet" />
	<!-- Font Awesome -->
	<link href="/assets/font-awesome.css" rel="stylesheet" />
	<!-- OWL Carousel -->
	<link href="/assets/owl.carousel.css" rel="stylesheet" />
	<!-- Jquery UI -->
	<link href="/assets/jquery-ui.css" rel="stylesheet" />
	<!--<link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">-->
    
    <link href="/assets/checkbox.css" rel="stylesheet" />
	<link href="/assets/index.css" rel="stylesheet" />
	<link href="/assets/prettyPhoto.css" rel="stylesheet" />
	<link href="/assets/about.css" rel="stylesheet" />
	<link href="/assets/user-page.css" rel="stylesheet" />
	
	<!--font-->
	<link href='//spoqa.github.io/spoqa-han-sans/css/SpoqaHanSans-kr.css' rel='stylesheet' type='text/css'>
	<link href='//spoqa.github.io/spoqa-han-sans/css/SpoqaHanSans-jp.css' rel='stylesheet' type='text/css'>
	
	
	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
	
	<div class="htlfndr-wrapper">
			<header>
				
				
				<div class="htlfndr-top-header">
					<div class="navbar navbar-default htlfndr-blue-hover-nav">
						<div class="container">
							<!-- Brand and toggle get grouped for better mobile display -->
							<div class="navbar-header">
								<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#htlfndr-first-nav">
									<span class="sr-only">Toggle navigation</span>
									<span class="icon-bar"></span>
									<span class="icon-bar"></span>
									<span class="icon-bar"></span>
								</button>
								<a class="htlfndr-logo navbar-brand" href="/home/index">
									<img src="/assets/tost_logo.gif" alt="Logo" style="width:8%;" />
								</a>
							</div><!-- .navbar-header -->
							<!-- Collect the nav links, forms, and other content for toggling -->
							<div class="collapse navbar-collapse navbar-right" id="htlfndr-first-nav">
								<!-- List with sing up/sing in links -->
								<ul class="nav navbar-nav htlfndr-singup-block">
									<% if current_user %> <!--로그인 한경우 -->
										<li id="htlfndr-singin-link">
											<a href="/home/index">
												<span onclick="DoNav('/index')">HOME</span></a>
										</li>
										
										<li id="htlfndr-singin-link">
											<a href="/home/user_page">
												<span onclick="DoNav('/user_page')">마이페이지</span></a>
										</li>
										
										<li id="htlfndr-singin-link">
											<a href="/home/about">
												<span onclick="DoNav('/about')">ABOUT</span></a>
										</li>
				
										<li id="htlfndr-singin-link">
											<a href="/users/sign_out">
												<span onclick="DoNav('/users/sign_out')">로그아웃</span></a>
										</li>
										
									<% else %> <!--로그인 안한경우 -->
										<li id="htlfndr-singin-link">
											<a href="/home/index">
												<span onclick="DoNav('/index')">HOME</span></a>
										</li>
										<li id="htlfndr-singin-link">
											<a href="#" data-toggle="modal" data-target="#layerpop"><span>로그인</span></a>
										</li>
										
										<li id="htlfndr-singup-link">
											<a href="/users/sign_up">
												<span onclick="DoNav('/users/sign_up')">회원가입</span></a>
										</li>
										
										<li id="htlfndr-singin-link">
											<a href="/home/about">
												<span onclick="DoNav('/about')">ABOUT</span></a>
										</li>
										
									<% end %>
								</ul><!-- .htlfndr-singup-block -->					
							</div><!-- .collapse.navbar-collapse -->
						</div><!-- .container -->
					</div><!-- .navbar.navbar-default.htlfndr-blue-hover-nav-->
				</div><!-- .htlfndr-top-header -->
				<noscript><h2>You have JavaScript disabled!</h2></noscript>
			</header>
	</div>

	
	</head>
	

<body>
	<%= yield %>
	
		<!--로그인-->
<input class="btn btn-default" input type="hidden" data-target="#layerpop" data-toggle="modal"></button><br/>
<div class="modal fade" id="layerpop" >
  <div class="modal-dialog">
    <div class="modal-content">
      <!-- header -->
      <div class="modal-header">
      	<img class="htlfndr-logo navbar-brand" src="/assets/tost_logo.gif" alt="Logo" />
        <!-- 닫기(x) 버튼 -->
        <button type="button" class="close" data-dismiss="modal">×</button>
      </div>
      <!-- body -->
      <div class="modal-body">
         	<div class="form">
		    <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
		    	<div style ="text-align:center"><%= flash[:alert] %></div> 
		    <div class="modal-field_id1" style="background-color:#f2f2f2">
		   	<img class="icon_user_modal" src="/assets/icon_user_id.png"/>
		   	<%= f.email_field :email, autofocus: true, :placeholder => "e-mail", :class =>"modal-field_id"%>
		    </div>
		    <div class="modal-field_id1" style="background-color:#f2f2f2">
		    <img class="icon_user_modal" src="/assets/icon_password.png"/>	
		    <%= f.password_field :password, :autocomplete => "off", :placeholder => "password", :class =>"modal-field_password"%>
		    </div>
		    <div class="actions">
		      <%= f.submit "로그인", :class => 'modal-button'%>
		      <% end %>
		  	</div>
		  	<div style="text-align:center"><%= render "devise/shared/links" %></div>
		 </div>
      </div>
      <!-- Footer -->
      <div class="modal-footer" style="text-align:auto">
        <div style="text-align:center"> 아직 토스트 회원이 아니세요? &nbsp;
        <a href="/users/sign_up"><span>회원가입</span></a></div>
      </div>
    </div>
  </div>
</div>
	
	<script src="/assets/jquery-1.11.3.min.js"></script>
	<!-- Include Jquery UI script file -->
	<script src="/assets/jquery-ui.min.js"></script>
		
	<!--common script for all pages / back to top-->
    <script src="/assets/common-scripts.js"></script>
    <script src="/assets/bootstrap.js"></script>
	<script src="/assets/custom.js"></script> 
	<script src="/assets/owl.carousel.js"></script> 
	<script src="/assets/script.js"></script>
	<script src="/assets/scrollReveal.js"></script> 	
	<script src="/assets/starrr.js"></script>
	<script src="/assets/tinysort.js"></script> 
	<script src="/assets/jquery.ui.touch-punch.min.js"></script>
	<script src="/assets/javascripts/jquery.glide.js"></script>
	<!-- Start of the Footer -->
	<footer class="htlfndr-footer">
				
		<div class="htlfndr-copyright">
			<div class="container" role="contentinfo">
				<p>멋쟁이사자처럼x성균관대학교 4팀</p>
			</div><!-- .container -->
		</div><!-- .htlfndr-copyright -->
	</footer>
	    
</body>
</html>